### ISSUE TITLE
CR009: Text comparison feature doesn't work at all times

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-roadmap#47]
## Background
The feature of comparing texts in different frames in the same window requires to compare chapters instead of versions of a given text.

Pecha.org has disabled the Versions/ས་བཅད། in simple texts to avoid showing a lone chapter in the chapter list. Because of that, when attempting to compare a simple text, chapters are hidden and the only thing left is the text's versions, which then leads to this bug.

## Location
Go:
- In "Resources" of any given text, 
- click on "Compare Text"
- Go until opening a chosen text

## Current behavior
Not finding the required chapter information, the web application refreshes the whole page and opens the version of the text, losing the text that was initially opened.

## Todo
devise a strategy to solve the issue, then implement it.

**Comment by kaldan007** [comment]
@Lungsangg and @lobsam please prepare a RFC for this one

**Comment by kaldan007** [comment]
draft [RFC](https://github.com/orgs/OpenPecha/projects/87/views/1?pane=issue&itemId=74607275)
