### ISSUE TITLE
CR008: Tibetan text not displaying well

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-roadmap#53]
## top or bottom (or both) of Tibetan text is cut off

- [x] Top (and maybe bottom) is cut off in the title of texts
location: header of any open text

The `ོ` is cut off
![image](https://github.com/user-attachments/assets/b34d762c-d73c-4deb-b21a-4cb252d3d9c0)

- [x] Create New Sheet>>Save>>click on "share"

the tail of སྟོན། is cut off
![image](https://github.com/user-attachments/assets/668850a9-d807-4d09-8d9c-9fcda4681b51)

- [x] Open saved sheet >> share/བརྒྱུད་སྐུར།

the top and bottom is cut off
![image](https://github.com/user-attachments/assets/521e0efb-d29f-4a4b-a8b4-65e7925693cc)

- [x] change custom dropdown styling and padding
 ![Image](https://github.com/user-attachments/assets/e2f45fdc-b2e3-4231-84ae-9b2488e45464)

**Comment by lobsam** [comment]
@drupchen,in default html select option , spacing around list item is not supported by any browser . in order to do this we need to create custom dropdown list instead of using default html element one.

**Comment by drupchen** [comment]
@lobsam it works, the dropdown doesn't crop the Tibetan text.

Could we have the outer box and the down arrow just like in the Sefaria dropdown?
And not have the red color in the dropdown, and resize it as it was before (see screenshot in the description)?



![Image](https://github.com/user-attachments/assets/e2f45fdc-b2e3-4231-84ae-9b2488e45464)

**Comment by lobsam** [comment]
@drupchen la i have chaged dropdown styling and padding as per your mentioned. you can test it now

**Comment by drupchen** [comment]
Thanks. It's better. could you add the same box as the one which contains ཚོད་ལྟ། ?

Then apply it to that dropdown.

![Image](https://github.com/user-attachments/assets/775c3101-78de-4d04-b285-eca366778a36)
